### ISSUE TITLE
Not working on latest MuseScore (v1.3)

### ISSUE THREAD

**Issue by alejandroiglesias** [Jojo-Schmitz/microtune#2]
Hey guys, i would like to congratulate you for your work on this. It's great for us who work with eastern music. Sadly, i couldn't make the plugin play the quarters. Is the plugin still compatible with MuseScore 1.3? Otherwise, is it possible to update it?
Thanks and best regards.

**Comment by davideCremona** [comment]
what for version 2.0.9?

**Comment by Jojo-Schmitz** [comment]
There is no 2.0,.9, but anyway this plugin does not work with 2.x
